### ISSUE TITLE
How to connect the mindwave with pi

### ISSUE THREAD

**Issue by bbbbear** [robintibor/python-mindwave-mobile#10]
As I try to connect the mindwave with the rasperry pi, it shows an error:
Connection failed - No usable services on this device.

**Comment by robintibor** [comment]
Hm, unfortunately I own no rasperry pi and no longer have access to the mindwave :( But please write if you find some solution. Do other bluetooth connections work?

**Comment by bbbbear** [comment]
It's working now, its my fault.
Everything is fine, thank you.
