### ISSUE TITLE
Reading Meditation and Blinkstrength simultaneoulsy

### ISSUE THREAD

**Issue by musharrafleo95** [robintibor/python-mindwave-mobile#12]
Hello Robin,
 I am doing my project on mindwave mobile home appliance automation. For this project to work i want to read a specific data point. so by searching in your github python-mindwave-mobile i found a issue whose link is " https://github.com/robintibor/python-mindwave-mobile/issues/3#issuecomment-68265855 ". After trying the code you gave in there i did get a specific EEG signals also got specific waves. After i tried the same for Meditation signal and that also worked. 

but the problem is i want to use two data points simultaneously. "blink data point" for operating  and selecting the appliance and "meditation data point" to control the speed and I only want to use their values because when I printed the meditation data point I also got the sentence with it which is like "Meditation level = 55" so can you  tell me how to only get the value 55 so that i can use that value for different mathematical operation. and also how can i not just print but also use these variable after i have gotten there value.

Sorry for the long post because I am an electrical(power) student and I only learned C language in the programming course. Since  I am doing it on raspberry pi so i had to learn python and r pi from scratch.
So if you can please reply me :P and thanks for this awesome library.

**Comment by robintibor** [comment]
Sorry I missed this beforem I tihink there is no blink output directly, see https://github.com/robintibor/python-mindwave-mobile/issues/1#issuecomment-9321936 Did you manage to do something yourself or no longer interested?

**Comment by musharrafleo95** [comment]
Hello there, Thanks for replying yeah i did manage to get the meditation value in integer format by this code.
 dataPoint = mindwaveDataPointReader.readNextDataPoint()

  if dataPoint.__class__.__name__ == 'MeditationDataPoint':
          x = int(MeditationDataPoint.meditationValue)

but since my mindwave is not giving correct signal so i dont know if it was working correctly or not. and about the blink i wrote the same above code with blink data point but i have not checked it yet. but from the link  #1 (comment) i think it will not work so i will try with the raw eeg value.

Thanks for your time and this library.

**Comment by robintibor** [comment]
yes I think blink you will not get, as mindwave doesnt provide as written in the link. so ya you can try to get blinks from analyzing the raw eeg value. thanks for your interest! reopen or open another issue in case of any further questions :)
