### ISSUE TITLE
How to turn on LED ?

### ISSUE THREAD

**Issue by leiw324** [robintibor/python-mindwave-mobile#17]
Hello robintibor,

I am trying to turn on LED, please see the following python, I set > 30 attention to turn on LED, but do nothing:

#!/usr/bin/python
import RPi.GPIO as GPIO
import time
import bluetooth

from mindwavemobile.MindwaveDataPoints import RawDataPoint
from mindwavemobile.MindwaveDataPointReader import MindwaveDataPointReader

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(13,GPIO.OUT)

if __name__=='__main__':
   mindwaveDataPointReader = MindwaveDataPointReader(address='CC:78:AB:77:69:13')
   mindwaveDataPointReader.start()
   if (mindwaveDataPointReader.isConnected()):
       while True:
         dataPoint = mindwaveDataPointReader.readNextDataPoint()
         if hasattr(dataPoint, 'attentionValue'):
            if dataPoint > 30:
                  GPIO.output(13,GPIO.HIGH)

**Comment by robintibor** [comment]
Uh I cannot tell. Do you actually get attention values at all? maybe print them?
