### ISSUE TITLE
anyone can help me .....How to read blink signals

### ISSUE THREAD

**Issue by Zana12345** [robintibor/python-mindwave-mobile#18]
hello Robin can you help me to get the blink signal of mind wave mobile by raspberry pi i can get the other signals like Attention signals  but i cannot get the blink signals do you have any idea to get it is signals 
can you help me....?

**Comment by robintibor** [comment]
Hi @Zana12345 , 
unfortunately there is never a blink signal from the mindwave mobile, you'd have to detect blinks yourself, see https://github.com/robintibor/python-mindwave-mobile/issues/1#issuecomment-9321936
