### ISSUE TITLE
How do I get only Attention value?

### ISSUE THREAD

**Issue by osamaakram01** [robintibor/python-mindwave-mobile#20]
Hey Robintobor,
I am trying to get only the attention values that I want to use in my program for further manipulations. Unfortunately I am unable to get only attention value because your program gives all values including EEG,medications etc. 
Can you please help here?

**Comment by robintibor** [comment]
Hi! Please have a look at https://github.com/robintibor/python-mindwave-mobile/issues/3 and https://github.com/robintibor/python-mindwave-mobile/issues/12  that should solve it.
