### ISSUE TITLE
Error when running MindwavePacketPayloadParser.py file line 42

### ISSUE THREAD

**Issue by batuhangundogdu** [robintibor/python-mindwave-mobile#9]
Hello, I'm having trouble getting datas from my MindWave Mobile device. Here is the error of the sample program I ran. How can I run and test the device ? Thanks for your help.

Discovered Mindwave Mobile...

Traceback (most recent call last):
  File "/home/pi/Desktop/python-mindwave-mobile/deneme.py", line 7, in <module>
    dataPoint = mindwaveDataPointReader.readNextDataPoint()
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 20, in readNextDataPoint
    self._putNextDataPointsInQueue()
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 30, in _putNextDataPointsInQueue
    dataPoints = self._readDataPointsFromOnePacket()
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 40, in _readDataPointsFromOnePacket
    dataPoints = self._readDataPointsFromPayload(payloadBytes)
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwaveDataPointReader.py", line 78, in _readDataPointsFromPayload
    return payloadParser.parseDataPoints();
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwavePacketPayloadParser.py", line 15, in parseDataPoints
    dataPoint = self._parseOneDataPoint()
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwavePacketPayloadParser.py", line 23, in _parseOneDataPoint
    dataRowCode = self._extractDataRowCode();
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwavePacketPayloadParser.py", line 28, in _extractDataRowCode
    return self._ignoreExtendedCodeBytesAndGetRowCode()
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwavePacketPayloadParser.py", line 35, in _ignoreExtendedCodeBytesAndGetRowCode
    byte = self._getNextByte()
  File "/home/pi/Desktop/python-mindwave-mobile/mindwavemobile/MindwavePacketPayloadParser.py", line 42, in _getNextByte
    nextByte = self._payloadBytes[self._payloadIndex]
IndexError: list index out of range

**Comment by robintibor** [comment]
Unfortunately I do not own a mindwave mobile anymore, if I have access to one I can try to reproduce this.

**Comment by tayyabahmad** [comment]
@batuhangundogdu did you found a solution to this problem? im getting the same issue.

**Comment by batuhangundogdu** [comment]
@tayyabahmad no, I couldn't find. Instead, I figured the problem out with using a JavaScript program, which does the same thing as Python.

**Comment by robintibor** [comment]
@batuhangundogdu  Can you share this JavaScript program?

**Comment by batuhangundogdu** [comment]
Sure, here it is [https://github.com/afiedler/node-thinkgear-sockets](url)

**Comment by batuhangundogdu** [comment]
@robintibor @tayyabahmad Sure, here it is :
[https://github.com/batuhangundogdu/node-thinkgear-sockets](url)

**Comment by a1noack** [comment]
@robintibor @tayyabahmad @batuhangundogdu I am getting the same error.  Does anyone have any other suggestions?

**Comment by a1noack** [comment]
@robintibor @tayyabahmad @batuhangundogdu I got it to work. It seems that the mindwave mobile adjusted its protocol and a few unaccounted for commands are included in the data stream from the device. At the beginning of each successful connection to the client, the mindwave mobile seems to broadcast two bytes 0xBA, 0xBC. These byte values are not accounted for in the MindwavePacketPayloadParser.py methods. To fix this I changed the code for these two methods in MindwavePacketPayloadParser.py to:
```
    def _extractLengthOfValueBytes(self, dataRowCode):
        dataRowHasLengthByte = dataRowCode > 0x7f and dataRowCode < 0x85
        if (dataRowHasLengthByte):
            return self._getNextByte() 
        else:
            return 1
        
    def _createDataPoint(self, dataRowCode, dataRowValueBytes):
        if (dataRowCode == 0x02):
            return PoorSignalLevelDataPoint(dataRowValueBytes)
        elif (dataRowCode == 0x04):
            return AttentionDataPoint(dataRowValueBytes)
        elif (dataRowCode == 0x05):
            return MeditationDataPoint(dataRowValueBytes)
        elif (dataRowCode == 0x16):
            return BlinkDataPoint(dataRowValueBytes)
        elif (dataRowCode == 0x80):
            return RawDataPoint(dataRowValueBytes)
        elif (dataRowCode == 0x83):
            return EEGPowersDataPoint(dataRowValueBytes)
        elif (dataRowCode == 0xbc or dataRowCode == 0xba): #handles strange initial command signals
            return None
        else:
            assert False
```

**Comment by tayyabahmad** [comment]
Thanks @a1noack  i'll test it soon then let you know if you solved my BIG problem. i'm still stuck with Neurosky issues.

**Comment by tayyabahmad** [comment]
@a1noack No success with your solution as well. can you please see if you have changed anything else as well ?

**Comment by a1noack** [comment]
@tayyabahmad sorry, just seeing this. I checked again I am pretty certain that those two methods are the only ones that I changed. Is the error you're getting still exactly the same as before?
